export interface IData {
  foodName: string;
  foodImage: string;
  price: string;
  restaurantName: string;
  rating: number;
  isActive: 'yes' | 'no';
}

export const data: IData[] = [
  {
    foodName: 'Spaghetti Carbonara',
    foodImage: 'https://example.com/images/spaghetti.jpg',
    price: '12.99',
    restaurantName: 'Italiano Delight',
    rating: 4,
    isActive: 'yes',
  },
  {
    foodName: 'Margherita Pizza',
    foodImage: 'https://example.com/images/pizza.jpg',
    price: '9.5',
    restaurantName: 'Pizza Palace',
    rating: 5,
    isActive: 'yes',
  },
  {
    foodName: 'Caesar Salad',
    foodImage: 'https://example.com/images/caesar-salad.jpg',
    price: '7.0',
    restaurantName: 'Fresh Greens',
    rating: 3,
    isActive: 'no',
  },
  {
    foodName: 'Beef Burger',
    foodImage: 'https://example.com/images/burger.jpg',
    price: '11.25',
    restaurantName: 'Burger Joint',
    rating: 4,
    isActive: 'yes',
  },
  {
    foodName: 'Sushi Platter',
    foodImage: 'https://example.com/images/sushi.jpg',
    price: '20.0',
    restaurantName: 'Sakura Sushi',
    rating: 5,
    isActive: 'yes',
  },
  {
    foodName: 'Chicken Tikka Masala',
    foodImage: 'https://example.com/images/tikka-masala.jpg',
    price: '14.99',
    restaurantName: 'Spice Route',
    rating: 4,
    isActive: 'yes',
  },
  {
    foodName: 'Vegetable Stir Fry',
    foodImage: 'https://example.com/images/stir-fry.jpg',
    price: '8.75',
    restaurantName: 'Wok This Way',
    rating: 3,
    isActive: 'no',
  },
  {
    foodName: 'Fish and Chips',
    foodImage: 'https://example.com/images/fish-chips.jpg',
    price: '13.5',
    restaurantName: 'Seafood Shack',
    rating: 4,
    isActive: 'yes',
  },
  {
    foodName: 'Tacos Al Pastor',
    foodImage: 'https://example.com/images/tacos.jpg',
    price: '9.0',
    restaurantName: 'Taco Town',
    rating: 5,
    isActive: 'yes',
  },
  {
    foodName: 'Pad Thai',
    foodImage: 'https://example.com/images/pad-thai.jpg',
    price: '12.0',
    restaurantName: 'Thai Spice',
    rating: 4,
    isActive: 'yes',
  },
  {
    foodName: 'French Onion Soup',
    foodImage: 'https://example.com/images/french-onion.jpg',
    price: '7.5',
    restaurantName: 'Bistro Paris',
    rating: 3,
    isActive: 'no',
  },
  {
    foodName: 'Chocolate Lava Cake',
    foodImage: 'https://example.com/images/lava-cake.jpg',
    price: '6.5',
    restaurantName: 'Sweet Tooth',
    rating: 5,
    isActive: 'yes',
  },
  {
    foodName: 'Grilled Salmon',
    foodImage: 'https://example.com/images/grilled-salmon.jpg',
    price: '18.0',
    restaurantName: "Ocean's Catch",
    rating: 4,
    isActive: 'yes',
  },
  {
    foodName: 'Greek Salad',
    foodImage: 'https://example.com/images/greek-salad.jpg',
    price: '8.0',
    restaurantName: 'Mediterraneo',
    rating: 3,
    isActive: 'no',
  },
  {
    foodName: 'Lamb Gyro',
    foodImage: 'https://example.com/images/lamb-gyro.jpg',
    price: '10.0',
    restaurantName: 'Gyro House',
    rating: 4,
    isActive: 'yes',
  },
  {
    foodName: 'Pancakes',
    foodImage: 'https://example.com/images/pancakes.jpg',
    price: '7.0',
    restaurantName: 'Breakfast Club',
    rating: 5,
    isActive: 'yes',
  },
  {
    foodName: 'BBQ Ribs',
    foodImage: 'https://example.com/images/bbq-ribs.jpg',
    price: '19.0',
    restaurantName: "Smokey's",
    rating: 4,
    isActive: 'yes',
  },
  {
    foodName: 'Veggie Burger',
    foodImage: 'https://example.com/images/veggie-burger.jpg',
    price: '10.5',
    restaurantName: 'Green Eats',
    rating: 4,
    isActive: 'no',
  },
  {
    foodName: 'Clam Chowder',
    foodImage: 'https://example.com/images/clam-chowder.jpg',
    price: '9.5',
    restaurantName: 'Harbor Diner',
    rating: 3,
    isActive: 'yes',
  },
  {
    foodName: 'Cheesecake',
    foodImage: 'https://example.com/images/cheesecake.jpg',
    price: '6.0',
    restaurantName: 'Dessert Haven',
    rating: 5,
    isActive: 'yes',
  },
];
